<?php

namespace Acme\SearchBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ClipController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\SearchBundle\Controller\ClipController();
        return $instance;
    }
}
